apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ai-uploader.<YOUR_DOMAIN>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-backend-service
                port:
                  number: 80

